import Foundation
import SwiftCardanoTxValidator
import TxWorkshopCore

/// A transaction written out for people (Markdown) or programs (JSON).
public struct TransactionReport: Sendable {
    public let inspection: TransactionInspection
    public let transaction: Data
    public let network: CardanoNetwork?
    public let notes: String

    public init(inspection: TransactionInspection, transaction: Data, network: CardanoNetwork?, notes: String) {
        self.inspection = inspection
        self.transaction = transaction
        self.network = network
        self.notes = notes
    }

    /// Section headings for reports, in English.
    public static func heading(_ section: TransactionFact.Section) -> String {
        switch section {
        case .transaction: "Transaction"
        case .inputs: "Inputs"
        case .referenceInputs: "Reference inputs"
        case .collateral: "Collateral"
        case .outputs: "Outputs"
        case .mint: "Minted and burned"
        case .withdrawals: "Withdrawals"
        case .certificates: "Certificates"
        case .votes: "Votes"
        case .proposals: "Proposals"
        case .scripts: "Scripts"
        case .redeemers: "Redeemers"
        case .datums: "Datums"
        case .metadata: "Metadata"
        case .witnesses: "Witnesses"
        }
    }

    /// The facts, by section, in report order; empty sections are left out.
    public var sections: [(section: TransactionFact.Section, facts: [TransactionFact])] {
        let facts = inspection.facts
        return TransactionFact.Section.allCases.compactMap { section in
            let inSection = facts.filter { $0.section == section }
            return inSection.isEmpty ? nil : (section, inSection)
        }
    }

    // MARK: Markdown

    public func markdown(generatedAt date: Date = .now) -> String {
        var lines = ["# Transaction \(inspection.summary.id)", ""]
        if let network { lines.append("Network: \(network.id)  ") }
        lines.append("Generated by Tx Workshop on \(date.formatted(.iso8601)).")
        let trimmedNotes = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedNotes.isEmpty {
            lines += ["", "## Notes", "", trimmedNotes]
        }
        for (section, facts) in sections {
            lines += ["", "## \(Self.heading(section))", "", "| Field | Value |", "| --- | --- |"]
            lines += facts.map { "| \(Self.cell($0.label)) | \(Self.cell($0.value)) |" }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Table cell text: pipes escaped, line breaks flattened.
    static func cell(_ text: String) -> String {
        let flat = text.replacingOccurrences(of: "\r\n", with: " ").replacingOccurrences(of: "\n", with: " ")
        let escaped = flat.replacingOccurrences(of: "|", with: "\\|")
        return escaped.isEmpty ? "—" : escaped
    }

    // MARK: JSON

    struct Export: Encodable {
        let id: String
        let network: String?
        let notes: String?
        let cborHex: String
        let signers: [String]
        let transaction: TransactionView
        let facts: [Fact]

        struct Fact: Encodable {
            let section: TransactionFact.Section
            let key: String
            let label: String
            let value: String
        }
    }

    public func json() throws -> Data {
        let trimmedNotes = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        let export = Export(
            id: inspection.summary.id,
            network: network?.id,
            notes: trimmedNotes.isEmpty ? nil : trimmedNotes,
            cborHex: transaction.hex,
            signers: inspection.signers,
            transaction: inspection.view,
            facts: inspection.facts.map { .init(section: $0.section, key: $0.key, label: $0.label, value: $0.value) }
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return try encoder.encode(export)
    }
}
