import CoreGraphics
import SwiftUI
import TxWorkshopEngine

/// A transaction report as a paginated PDF, laid out on US Letter.
@MainActor
enum ReportPDF {
    static let pageSize = CGSize(width: 612, height: 792)
    /// The height rows may fill: the page less its margins, header and footer.
    static let bodyHeight: CGFloat = 620

    enum Row: Hashable {
        case heading(String)
        case fact(label: String, value: String)
        case note(String)
    }

    static func rows(for report: TransactionReport) -> [Row] {
        var rows: [Row] = []
        let notes = report.notes.trimmingCharacters(in: .whitespacesAndNewlines)
        if !notes.isEmpty {
            rows.append(.heading("Notes"))
            rows += notes.split(separator: "\n", omittingEmptySubsequences: false).map { .note(String($0)) }
        }
        for (section, facts) in report.sections {
            rows.append(.heading(TransactionReport.heading(section)))
            rows += facts.map { .fact(label: $0.label, value: $0.value) }
        }
        return rows
    }

    /// Roughly how tall a row draws. Values wrap onto a second line past
    /// about 100 monospaced characters.
    static func height(of row: Row) -> CGFloat {
        switch row {
        case .heading: 26
        case .fact(_, let value): value.count > 100 ? 40 : 30
        case .note: 18
        }
    }

    /// The rows split into pages that each fit ``bodyHeight``.
    static func pages(_ rows: [Row]) -> [[Row]] {
        var pages: [[Row]] = [[]]
        var used: CGFloat = 0
        for row in rows {
            let height = height(of: row)
            if used + height > bodyHeight, !pages[pages.count - 1].isEmpty {
                pages.append([])
                used = 0
            }
            pages[pages.count - 1].append(row)
            used += height
        }
        return pages
    }

    static func render(_ report: TransactionReport) -> Data {
        let pages = pages(rows(for: report))
        let data = NSMutableData()
        var box = CGRect(origin: .zero, size: pageSize)
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
            let pdf = CGContext(consumer: consumer, mediaBox: &box, nil)
        else { return Data() }
        for (number, page) in pages.enumerated() {
            let view = ReportPage(report: report, rows: page, number: number + 1, count: pages.count)
                .frame(width: pageSize.width, height: pageSize.height)
            ImageRenderer(content: view).render { _, draw in
                pdf.beginPDFPage(nil)
                draw(pdf)
                pdf.endPDFPage()
            }
        }
        pdf.closePDF()
        return data as Data
    }
}

/// One page of the report. Always light, whatever the app's appearance.
private struct ReportPage: View {
    let report: TransactionReport
    let rows: [ReportPDF.Row]
    let number: Int
    let count: Int

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(alignment: .firstTextBaseline) {
                Text(verbatim: "Transaction \(report.inspection.summary.id.prefix(16))…")
                    .font(.headline)
                Spacer()
                Text(verbatim: [report.network?.id, "Page \(number) of \(count)"].compactMap(\.self).joined(separator: " · "))
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Divider()
            ForEach(rows, id: \.self) { row in
                switch row {
                case .heading(let title):
                    Text(verbatim: title)
                        .font(.subheadline.bold())
                        .padding(.top, 6)
                case .fact(let label, let value):
                    VStack(alignment: .leading, spacing: 1) {
                        Text(verbatim: label)
                            .font(.caption)
                            .lineLimit(1)
                            .truncationMode(.middle)
                        Text(verbatim: value.isEmpty ? "—" : value)
                            .font(.system(size: 8, design: .monospaced))
                            .foregroundStyle(.secondary)
                            .lineLimit(2)
                            .truncationMode(.middle)
                    }
                case .note(let line):
                    Text(verbatim: line)
                        .font(.caption)
                }
            }
            Spacer(minLength: 0)
            Text(verbatim: "Generated by Tx Workshop")
                .font(.caption2)
                .foregroundStyle(.secondary)
        }
        .padding(40)
        .background(Color.white)
        .environment(\.colorScheme, .light)
    }
}
